#include <stddef.h>
long XGetGeometry(void){return 0L;}
long XSetIMValues(void){return 0L;}
long XInternAtoms(void){return 0L;}
long XPending(void){return 0L;}
long XF86VidModeQueryVersion(void){return 0L;}
long XCreateGC(void){return 0L;}
long XFreeCursor(void){return 0L;}
long XFixesHideCursor(void){return 0L;}
long XInitThreads(void){return 0L;}
long XSetLocaleModifiers(void){return 0L;}
long XSetErrorHandler(void){return 0L;}
long XPeekEvent(void){return 0L;}
long XSelectExtensionEvent(void){return 0L;}
long XAllowEvents(void){return 0L;}
long XKeysymToKeycode(void){return 0L;}
long XQueryColor(void){return 0L;}
long XSetWMProtocols(void){return 0L;}
long XDeleteProperty(void){return 0L;}
long XGetVisualInfo(void){return 0L;}
long XGetAtomName(void){return 0L;}
long XMapWindow(void){return 0L;}
long XDefineCursor(void){return 0L;}
long XGetImage(void){return 0L;}
long XStringListToTextProperty(void){return 0L;}
long XAllocSizeHints(void){return 0L;}
long XResourceManagerString(void){return 0L;}
long XGetWindowAttributes(void){return 0L;}
long XSetSelectionOwner(void){return 0L;}
long XSetInputFocus(void){return 0L;}
long XCreateFontCursor(void){return 0L;}
long XAllocClassHint(void){return 0L;}
long XUnsetICFocus(void){return 0L;}
long XGetExtensionVersion(void){return 0L;}
long XListInputDevices(void){return 0L;}
long XFreeDeviceList(void){return 0L;}
long XOpenDevice(void){return 0L;}
long XSetClassHint(void){return 0L;}
long XCreateWindow(void){return 0L;}
long XLookupKeysym(void){return 0L;}
long XSetIOErrorHandler(void){return 0L;}
long XSync(void){return 0L;}
long XSetWMHints(void){return 0L;}
long XSetTransientForHint(void){return 0L;}
long XSetWMClientMachine(void){return 0L;}
long XFetchName(void){return 0L;}
long XLowerWindow(void){return 0L;}
long XStoreName(void){return 0L;}
long XOpenIM(void){return 0L;}
long XGetSelectionOwner(void){return 0L;}
long XSetICFocus(void){return 0L;}
long XF86VidModeGetAllModeLines(void){return 0L;}
long XGetErrorText(void){return 0L;}
long XInternAtom(void){return 0L;}
long XGrabKeyboard(void){return 0L;}
long XDestroyWindow(void){return 0L;}
long XDrawString(void){return 0L;}
long XCloseDevice(void){return 0L;}
long XQueryPointer(void){return 0L;}
long XSelectInput(void){return 0L;}
long XQueryTree(void){return 0L;}
long XCreateColormap(void){return 0L;}
long XUngrabPointer(void){return 0L;}
long XCloseIM(void){return 0L;}
long XUngrabKeyboard(void){return 0L;}
long XMapRaised(void){return 0L;}
long XCheckMaskEvent(void){return 0L;}
long XNextEvent(void){return 0L;}
long XChangeProperty(void){return 0L;}
long XGetICValues(void){return 0L;}
long XDefaultColormap(void){return 0L;}
long XDefaultScreen(void){return 0L;}
long XFreeDeviceState(void){return 0L;}
long XQueryKeymap(void){return 0L;}
long XRootWindow(void){return 0L;}
long XCloseDisplay(void){return 0L;}
long XGetWindowProperty(void){return 0L;}
long XFreePixmap(void){return 0L;}
long XLookupString(void){return 0L;}
long XGrabPointer(void){return 0L;}
long XFilterEvent(void){return 0L;}
long XSetWMNormalHints(void){return 0L;}
long XF86VidModeSwitchToMode(void){return 0L;}
long XFreeGC(void){return 0L;}
long XCreateIC(void){return 0L;}
long XAllocWMHints(void){return 0L;}
long XCreateSimpleWindow(void){return 0L;}
long XGetInputFocus(void){return 0L;}
long XCheckIfEvent(void){return 0L;}
long XCreatePixmapCursor(void){return 0L;}
long XSendEvent(void){return 0L;}
long XFreeColors(void){return 0L;}
long XQueryDeviceState(void){return 0L;}
long XDestroyIC(void){return 0L;}
long XFillRectangle(void){return 0L;}
long XFixesShowCursor(void){return 0L;}
long XOpenDisplay(void){return 0L;}
long XFlush(void){return 0L;}
long XFree(void){return 0L;}
long XConfigureWindow(void){return 0L;}
long XAllocNamedColor(void){return 0L;}
long XConvertSelection(void){return 0L;}
long XWarpPointer(void){return 0L;}
long XRaiseWindow(void){return 0L;}
long XF86VidModeSetViewPort(void){return 0L;}
long XCreateBitmapFromData(void){return 0L;}
long XPutBackEvent(void){return 0L;}
long XTranslateCoordinates(void){return 0L;}
