#!/usr/bin/env python3
"""MTA:SA drop-in test resource generator.

Writes test_resource/ with:
    meta.xml, client.lua, model.dff + model.txd + model.col (when present)

client.lua loads the DFF (textures are auto-paired from the same-named
model.txd by engineReplaceModel), the COL (engineLoadCOL / engineReplaceCOL)
and spawns the model so you can see it and test the collision in-game.

Usage:
    python3 mta_resource.py --name <model> --dff <path.dff> [--col <path.col>]
                            [--col-failed-reason <text>]
"""
import argparse
import os
import shutil
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # FBX2MTA/


def make_test_resource(name, dff, col=None, col_failed_reason=None,
                       txd=None, verbose=True):
    """Generate the MTA:SA drop-in test resource (test_resource/)."""
    def log(msg):
        if verbose:
            line = f"[{time.strftime('%H:%M:%S')}] {msg}"
            print(line, flush=True)

    d = os.path.join(ROOT, "test_resource")
    os.makedirs(d, exist_ok=True)

    have_col = bool(col and os.path.exists(col))
    have_txd = bool(txd and os.path.exists(txd))
    if have_col:
        files = ['<file src="model.dff"/>', '<file src="model.col"/>']
        col_lua = (
            "-- collision: real COL generated by DragonFF COL export (GTA SA COL3)\n"
            "local colOk, colErr = engineLoadCOL('model.col')\n"
            "if not colOk then\n"
            "    print('COL LOAD FAILED: ' .. tostring(colErr))\n"
            "else\n"
            "    engineReplaceCOL(206, 'model.col')\n"
            "    print('COL LOADED + REPLACED OK')\n"
            "end\n"
        )
    else:
        files = ['<file src="model.dff"/>']
        col_lua = (
            f"-- NOTE: no collision available for this conversion: "
            f"{col_failed_reason or 'COL not generated'}\n"
        )
    if have_txd:
        files.append('<file src="model.txd"/>')
        txd_lua = ("-- 3) TXD (textures - auto-paired with the DFF by "
                   "engineReplaceModel)\n")
    else:
        txd_lua = (
            "-- 3) TXD: no textures found in this FBX (model renders "
            "untextured)\n\n"
        )

    meta = f"""<meta>
    <min_mta_version auth_id="" auth_version="1.5.9"></min_mta_version>
    <info author="FBX2MTA" name="{name} test" type="map" version="1.2" description="Automatic DFF + TXD + COL load test (FBX2MTA)"/>
    <script src="client.lua" type="client" cache="false" />
    {chr(10).join("    " + f for f in files)}
</meta>
"""
    open(os.path.join(d, "meta.xml"), "w").write(meta)

    lua = (
        "-- FBX2MTA automatic MTA:SA test: loads DFF + TXD + COL and spawns the model\n"
        "local slot = 206 -- test model slot (adder)\n\n"
        "-- 1) DFF (rendering)\n"
        "local ok, err = engineLoadDFF(0, 'model.dff')\n"
        "if not ok then\n"
        "    print('DFF LOAD FAILED: ' .. tostring(err))\n"
        "else\n"
        "    engineReplaceModel(slot, 'model.dff', 'model.txd')\n"
        "    print('DFF LOADED + MODEL REPLACED OK')\n"
        "end\n\n"
        "-- 2) COL (collision)\n"
        f"{col_lua}"
        f"{txd_lua}"
        "-- 4) spawn the model so you can see / walk on it\n"
        "local obj = createObject(slot, 100.0, 1.5, -1000.0, 0, 0, 0)\n"
        "if obj then\n"
        "    print('MODEL SPAWNED at (100.0, 1.5, -1000.0) - /goto obj')\n"
        "else\n"
        "    print('WARNING: model not spawned yet - type /goto adder after spawn')\n"
        "end\n"
    )
    open(os.path.join(d, "client.lua"), "w").write(lua)

    shutil.copyfile(dff, os.path.join(d, "model.dff"))
    if have_col:
        shutil.copyfile(col, os.path.join(d, "model.col"))
    if have_txd:
        shutil.copyfile(txd, os.path.join(d, "model.txd"))
    log(f"MTA test resource written to {d} (drop into MTASA/resources/{name}_test)")
    return d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--dff", required=True)
    ap.add_argument("--col", default="")
    ap.add_argument("--col-failed-reason", default="")
    args = ap.parse_args()
    out = make_test_resource(
        args.name, args.dff,
        col=args.col or None,
        col_failed_reason=args.col_failed_reason or None)
    print(f"TEST RESOURCE: {out}")


if __name__ == "__main__":
    main()
