-- FBX2MTA automatic MTA:SA test: loads DFF + COL and spawns the model
local slot = 206 -- test model slot (adder)

-- 1) DFF (rendering)
local ok, err = engineLoadDFF(0, 'model.dff')
if not ok then
    print('DFF LOAD FAILED: ' .. tostring(err))
else
    engineReplaceModel(slot, 'model.dff', 'model.txd')
    print('DFF LOADED + MODEL REPLACED OK')
end

-- 2) COL (collision)
-- collision: real COL generated by DragonFF COL export (GTA SA COL3)
local colOk, colErr = engineLoadCOL('model.col')
if not colOk then
    print('COL LOAD FAILED: ' .. tostring(colErr))
else
    engineReplaceCOL(206, 'model.col')
    print('COL LOADED + REPLACED OK')
end
-- 3) IFP (animation - MTA engineLoadIFP, GTA SA ANP3)
local ifpOk, ifpErr = engineLoadIFP('model.ifp')
if not ifpOk then
    print('IFP LOAD FAILED: ' .. tostring(ifpErr))
else
    print('IFP LOADED OK')
    -- plays on the player ped (needs matching skeleton, e.g.
    -- use your model as a custom ped: engineReplaceModel + createPed)
    setPedAnimation(localPlayer, 'generated_anim', 0, -1, -1, 1)
    print('ANIMATION PLAYING: generated_anim (setPedAnimation)')
end

-- 4) spawn the model so you can see / walk on it
local obj = createObject(slot, 100.0, 1.5, -1000.0, 0, 0, 0)
if obj then
    print('MODEL SPAWNED at (100.0, 1.5, -1000.0) - /goto obj')
else
    print('WARNING: model not spawned yet - type /goto adder after spawn')
end
